### ISSUE TITLE
Slow dev environment

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [riodwanto/superduper-filament-starter-kit#1]
Hello! First of all, let me thank you for the starter kit - it is pretty nice and made my day somewhat easier.

However, I'm having a very specific issue regarding loading time of the entire project. Literally everything takes too much time to load. How can I debug or troubleshoot this? Most pages are taking 11s-15s to load. 

I haven't made any major changes - I've only updated the locale from _en_ to _pt_BR_, and even setting it back to _en_ didn't perform any actual changes to the project performance.

Thx!

**Comment by fisecode** [comment]
solve the issue with
`php artisan icons:cache`
it works on me

source https://stackoverflow.com/questions/77167223/laravel-filament-very-slow

**Comment by riodwanto** [comment]
> solve the issue with `php artisan icons:cache` it works on me
> 
> source https://stackoverflow.com/questions/77167223/laravel-filament-very-slow

Hi @BRGustavoRibeiro ,

have u try solution from @fisecode ? It's suggested in the [Filament Documentation](https://filamentphp.com/docs/3.x/panels/installation#improving-filament-panel-performance) for Local and Production.

**Comment by BRGustavoRibeiro** [comment]
Hi guys! `php artisan icons:cache` fixed it for me.
Thanks for the help!
