### ISSUE TITLE
Failed to update settings.

### ISSUE THREAD

**Issue by iamalvenclaychuck** [riodwanto/superduper-filament-starter-kit#15]
PHP 8.3

I am so sorry for bothering but i got `Failed to update settings.` error when save changes in setting page, i installed this kit yet with new released master branch. Please help, thanks

**Comment by riodwanto** [comment]
Hi @iamalvenclaychuck ,

please attach screenshot the error you mention.
just to make it clear you're using PHP 8.3 with latest v1.14.2 right ?

**Comment by iamalvenclaychuck** [comment]
> Hi @iamalvenclaychuck ,
> 
> please attach screenshot the error you mention. just to make it clear you're using PHP 8.3 with latest v1.14.2 right ?

Oh! i am so sorry for replying late, currently i am using PHP 8.1, i will upgrade PHP and fresh install and update you, thanks a lot

**Comment by iamalvenclaychuck** [comment]
@riodwanto Found the problem for people who cannot figure it out!! you need to change `Brand Name*\Site Favicon* and Brand Logo*` together then it will be saved successfully

**Comment by riodwanto** [comment]
i see, it supposed to be thrown err instead of failed notification. thanks @iamalvenclaychuck
