### ISSUE TITLE
Blog Post Search issue

### ISSUE THREAD

**Issue by fisecode** [riodwanto/superduper-filament-starter-kit#2]
When searching on a blog post a query error occurred. For details, see this https://flareapp.io/share/pPvBrRoP

**Comment by riodwanto** [comment]
My bad.. since this project use accessor column for `name`. you can solve with `searchable(['firstname', 'lastname'])`. 

like this:
```
Tables\Columns\TextColumn::make('author.name')
         ->searchable(['firstname', 'lastname'])
         ...
```


i'll fixed base code on the next update.
