### ISSUE TITLE
Exception when creating a new user

### ISSUE THREAD

**Issue by romerpt** [riodwanto/superduper-filament-starter-kit#3]
Hi there,

First, nice job on the starter kit.

So I have found that when trying to create a new user I'm getting the below exception.

I currently running on php 8.3.3.

![ulaa_rowwkEJKYR](https://github.com/riodwanto/superduper-filament-starter-kit/assets/8874242/667b1d78-43f6-4f56-b94a-c3d188a9a472)

Thanks

**Comment by riodwanto** [comment]
Hi @romerpt , you can replace existing relationship & options with: `->relationship('roles', 'name')`

The final code should look like this:
```
...
Select::make('roles')->label('Role')
                    ->relationship('roles', 'name')
                    ->native(false)
...
```

**Comment by romerpt** [comment]
Hi, 

I have done that before to make it work.

Thanks
