### ISSUE TITLE
Throwing error 500 when trying to add user.

### ISSUE THREAD

**Issue by retamayo** [riodwanto/superduper-filament-starter-kit#4]
Hi, thank you for the nice template here.
Though I'm having trouble creating a user
Whenever I try to create a user by pressing add in the user resource I receive Error 500.

![image](https://github.com/riodwanto/superduper-filament-starter-kit/assets/67304955/2de7c890-372c-45e5-8957-5d37e0fc0203)

**Comment by riodwanto** [comment]
Hi @retamayo , 

You can see [this post](https://github.com/riodwanto/superduper-filament-starter-kit/issues/3#issuecomment-1986849789) to solve it.

**Comment by retamayo** [comment]
Thanks man appreciate it.
