### ISSUE TITLE
Filament Shield - Posts, Categories and Exclusions not working

### ISSUE THREAD

**Issue by romerpt** [riodwanto/superduper-filament-starter-kit#5]
Hi,

Just found another issue, when I create a new role and try to exclude Posts, Categories and Exception it is not working.

For the exception I found that was missing in the app/Providers/AuthServiceProvider the entry  Exception::class => ExceptionPolicy::class in the policies, but still not working.

Even tried generating a new policies for all but still not working.

Can you help me identify what I am missing here?

Thanks

**Comment by riodwanto** [comment]
try manual binding model with policy in `app/Providers/AuthServiceProvider`

```
use App\Models\Blog\Category;
use App\Models\Blog\Post;
use App\Policies\Blog\CategoryPolicy;
use App\Policies\Blog\PostPolicy;
use App\Policies\ExceptionPolicy;
use BezhanSalleh\FilamentExceptions\Models\Exception;

protected $policies = [
        ...
        Category::class => CategoryPolicy::class,
        Post::class => PostPolicy::class,
        Exception::class => ExceptionPolicy::class,
        ...
];
```

**Comment by romerpt** [comment]
Hi,

It is that, everything is running now.

Thanks for the help

**Comment by riodwanto** [comment]
Glad to help 🥂
