### ISSUE TITLE
when installing this package, the error happens with laravel/ignition package

### ISSUE THREAD

**Issue by holiccoder** [riodwanto/superduper-filament-starter-kit#6]
![13112935](https://github.com/riodwanto/superduper-filament-starter-kit/assets/38061345/7c55f7b0-f47d-472b-ab43-8d11eec3a72e)
PHP version: 8.2

**Comment by riodwanto** [comment]
Hi,
have u found solution yet ?
i think somehow your antivirus locked files from spatie/laravel-ignition. You can try remove spatie/laravel-ignition from composer.json - remove composer.lock & vendor - do composer install again, see if still getting error.

**Comment by holiccoder** [comment]
don't you have that problem? have you tried?

**Comment by paulmercs** [comment]
Hi riodwanto, when will you release the filament starter kit with multi-tenancy? 💯

**Comment by riodwanto** [comment]
> don't you have that problem? have you tried?

Nope, no issue for me. Maybe because I'm using difference os



> Hi riodwanto, when will you release the filament starter kit with multi-tenancy? 💯

Within the next week, hopefully.
