### ISSUE TITLE
readme fix

### ISSUE THREAD

**Issue by quasiperfect** [riodwanto/superduper-filament-starter-kit#7]
hi 

thanks for your work.

change the description for 

[Tapp Network - Laravel Auditing](https://filamentphp.com/plugins/tapp-network-laravel-auditing) : Resource locking when other user begins editing a resource.
[Shuvro Roy - Spatie Laravel Health](https://filamentphp.com/plugins/shuvroroy-spatie-laravel-health) : Resource locking when other user begins editing a resource.

**Comment by riodwanto** [comment]
Ah, thanks for reminding
