### ISSUE TITLE
Change logo and favicon not success

### ISSUE THREAD

**Issue by lutfiidham** [riodwanto/superduper-filament-starter-kit#9]
Terima kasih atas plugin yang keren ini, bang.
I’m consistently encountering a failure when attempting to update the logo and favicon; it results in a ‘404 not found’ error for the logo. It appears that the file in livewire-tmp has been successfully moved, but the filename has not been renamed as expected.
What should I do?

![image](https://github.com/riodwanto/superduper-filament-starter-kit/assets/21997116/c5cd2bf8-d115-42c8-b9aa-c9cde9b8004b)

**Comment by riodwanto** [comment]
Samii2 @lutfiidham ,

It's been fixed and merged on branch Master last week but not released yet. You can see merged history [here](https://github.com/riodwanto/superduper-filament-starter-kit/commit/07a440a20802868c224edd85718d8e259089848a) or see latest code from Master Branch.

**Comment by lutfiidham** [comment]
Mantap. Thanks! ✨

**Comment by iamalvenclaychuck** [comment]
I am so sorry for bothering but i got `Failed to update settings.` error when save changes in setting page, i installed this kit yet with new released master branch. Please help, thanks
